server:
  port: 8082

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:1200/team2db
    username: postgres
    password: quang232003
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: iceteasoftware.training@gmail.com
    password: xdrzojeruqavxpzw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Mail templates
  # Directory inside main/resources or absolute filesystem path
  templates:
    path: mail-templates
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: noti-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
