server:
  port: 8888

app:
  api-prefix: /api/v1

jwt:
  secret : ajMywt0FWnZYET/u3Pm309ziD6eXRewGX+QsyHs6/Y4ascWDHAAK46ARsuUZKLcjMQxUa5mQfNTaujgm8Sg4TJh4wKGwwXBAtB2gsEm1TkZuSRo97/BEFIR5rEKefTBf41J4kcU/YndvNFJcMRXkgMoC6fvzjSVYx1fGNYxSJqO+neilVm3uBpQiuhQrhTMmrKZJYa5M9xutWfJsbQ1Tf6IQ6zlRKZqdt8edUD/mOuUwltlyC1UZCyALrcji2vFlgXu+eks6IjBkxlAT3LvwVe5Et4MoNaB+eHetIdL6epigf1nYxmLSPT3rWfQxRRmHAwSQnO+1atAubG/xQqvsTQ==

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  #  main:
  #    web-application-type: reactive
  cloud:
    gateway:
      mvc:
        routes:
          - id: iam-service
            uri: http://localhost:8081
            predicates:
              - Path=${app.api-prefix}/auth/**
            filters:
              - StripPrefix=2
          - id: config-service
            uri: http://localhost:8085
            predicates:
              - Path=${app.api-prefix}/config/**
            filters:
              - StripPrefix=2
          - id: notification-service
            uri: http://localhost:8083
            predicates:
              - Path=${app.api-prefix}/noti/**
            filters:
              - StripPrefix=2
          - id: wallet-service
            uri: http://localhost:8086
            predicates:
              - Path=${app.api-prefix}/wallet/**
            filters:
              - StripPrefix=2
          - id: transaction-service
            uri: http://localhost:8084
            predicates:
              - Path=${app.api-prefix}/transaction/**
            filters:
              - StripPrefix=2
          - id: user-service
            uri: http://localhost:8082
            predicates:
              - Path=${app.api-prefix}/user/**
            filters:
              - StripPrefix=2