server:
  port: 8086
  servlet:
    context-path: /wallet
logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG
spring:
  application:
    name: wallet-service
  task:
    scheduling:
      pool:
        size: 5
  datasource:
    url: jdbc:postgresql://localhost:5432/team2db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    basename: i18n/labels
    cache-duration: 60
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: wallet-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
cache:
  config-type: 'redisson'
  redisson:
    mode: single
    single:
      address: 'redis://localhost:6379'
      password: ''
      clientName: 'my-redis-client'
      connectionMinimumIdleSize: 24
      connectionPoolSize: 64
      subscriptionConnectionPoolSize: 50
      subscriptionConnectionMinimumIdleSize: 1
    retryAttempts: 3
    retryInterval: 1500 # Đặt giá trị khác 0
    idleConnectionTimeout: 10000 # Đặt giá trị khác 0
    connectTimeout: 10000
    timeout: 3000
  time-to-lives:
    default: -1
    token: 300
    remember-me-token: 7200
    refresh-token: 86400
    otp: 180
    otp-verify: 3600
    temp-file: 3600
    login-failed: 86400
    captcha: 300
    password-verify: 300
    customer_draft_password: 300
    apiGee_getToken: 300
    customer_verify_password_failed: 3600

security:
  authentication:
    jwt:
      base64-secret: 'ajMywt0FWnZYET/u3Pm309ziD6eXRewGX+QsyHs6/Y4ascWDHAAK46ARsuUZKLcjMQxUa5mQfNTaujgm8Sg4TJh4wKGwwXBAtB2gsEm1TkZuSRo97/BEFIR5rEKefTBf41J4kcU/YndvNFJcMRXkgMoC6fvzjSVYx1fGNYxSJqO+neilVm3uBpQiuhQrhTMmrKZJYa5M9xutWfJsbQ1Tf6IQ6zlRKZqdt8edUD/mOuUwltlyC1UZCyALrcji2vFlgXu+eks6IjBkxlAT3LvwVe5Et4MoNaB+eHetIdL6epigf1nYxmLSPT3rWfQxRRmHAwSQnO+1atAubG/xQqvsTQ=='