server:
  port: 8086
  servlet:
    context-path: /wallet

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:1200/team2db
    username: postgres
    password: quang232003
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    basename: i18n/labels
    cache-duration: 60
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: wallet-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
