server:
  port: 8085  # Port for Config Service

jwt:
    secret : 0aPglnnROU/zGjIuvAA32LpDzmqEY2O7J4fgQ4Eh+4KuJaSCXQIFQgBv6a69Pvkt

spring:
  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1
  application:
    name: config-service
  messages:
    encoding: 'UTF-8'   # Đảm bảo mã hóa đúng
    use-code-as-default-message: true  # Sử dụng code làm thông điệp mặc định nếu không tìm thấy thông điệp
    basename: i18n/labels  # Đảm bảo đúng tên file (không cần đuôi .properties trong basename)
    cache-duration: 60   # Thời gian cache (60 giây)

  datasource:
    url: jdbc:postgresql://localhost:5431/team2db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  openapi:
#    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL for Eureka Server
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
