server:
    port: 8081

spring:
    application:
        name: iam-service
    datasource:
        url: jdbc:postgresql://localhost:5432/team2db
        username: postgres
        password: 123
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
        encoding: 'UTF-8'
        use-code-as-default-message: true
        basename: i18n/labels
        cache-duration: 60
    kafka:
        producer:
            bootstrap-servers: localhost:9094
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    data:
        redis:
            host: localhost
            port: 6379

security:
    cache:
        url-patterns: '/i18n/*,/content/*,/app/*'
        max-age: 86400 # Image cache max-age in second, duration: 86400 (1 day)
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: '*'
        allowed-methods: 'POST,OPTIONS,GET,PUT,DELETE'
        allowed-headers: '*'
        exposed-headers: 'Authorization,Link,X-Total-Count,X-Action-Message,X-Action-Params'
        allow-credentials: true
        max-age: 3600
    authentication:
        jwt:
            # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
            base64-secret: 'ajMywt0FWnZYET/u3Pm309ziD6eXRewGX+QsyHs6/Y4ascWDHAAK46ARsuUZKLcjMQxUa5mQfNTaujgm8Sg4TJh4wKGwwXBAtB2gsEm1TkZuSRo97/BEFIR5rEKefTBf41J4kcU/YndvNFJcMRXkgMoC6fvzjSVYx1fGNYxSJqO+neilVm3uBpQiuhQrhTMmrKZJYa5M9xutWfJsbQ1Tf6IQ6zlRKZqdt8edUD/mOuUwltlyC1UZCyALrcji2vFlgXu+eks6IjBkxlAT3LvwVe5Et4MoNaB+eHetIdL6epigf1nYxmLSPT3rWfQxRRmHAwSQnO+1atAubG/xQqvsTQ=='
        cookie:
            domain-name:
            enable-ssl: false
            http-only: true
            path: '/'
            same-site: 'Strict'
    login:
        max-attempt-time: 5
    password:
        max-attempt-time: 5

eureka:
    client:
        server-url:
            defaultZone: http://localhost:8761/eureka/

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
