server:
    port: 8081

spring:
    application:
        name: iam-service
    datasource:
        url: jdbc:postgresql://localhost:5432/team2db
        username: postgres
        password: root
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
        encoding: 'UTF-8'
        use-code-as-default-message: true
        basename: i18n/labels
        cache-duration: 60
    kafka:
        producer:
            bootstrap-servers: localhost:9094
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    data:
        redis:
            host: localhost
            port: 6379
eureka:
    client:
        server-url:
            defaultZone: http://localhost:8761/eureka/